replicaCount: 1

image:
  repository: vanshikaachaudhary/auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: auth.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
